### ISSUE TITLE
Error during installing the OpenShift templates

### ISSUE THREAD

**Issue by LyashenkoGS** [donovanmuller/spring-cloud-dataflow-server-openshift#21]
According to https://donovanmuller.github.io/spring-cloud-dataflow-server-openshift/docs/1.1.0.RELEASE/reference/htmlsingle/#getting-started
I encountered an error during installing templates.
`Adding 'scdf' Service Account to the 'anyuid' SCC...
Error from server (Forbidden): User "admin" cannot get securitycontextconstraints at the cluster scope`
MacBook Pro 2015; OS Sierra; VirtualBox 5.1.22; minishift-1.3.1-darwin-amd64
**How to reproduce**

 ```
 minishift start --memory 4028 --cpus 4 --vm-driver virtualbox --openshift-version v1.4.1 
  eval $(minishift oc-env)
  oc login --username=admin --password=admin
  oc new-project scdf --description="Spring Cloud Data Flow"
  curl https://raw.githubusercontent.com/donovanmuller/spring-cloud-dataflow-server-openshift/v1.1.0.RELEASE/src/etc/openshift/install-templates.sh | bash
```

**Comment by donovanmuller** [comment]
Thanks for the feedback.

The issue is that your `admin` user does not have the `cluster-admin` role by default.
You can use a minishift [addon](https://docs.openshift.org/latest/minishift/using/addons.html) to enable that before you start your minishift instance.

```console
$ minishift addons list
-- Installing default add-ons ... OK
- admin-user     : disabled   P(0)
- anyuid         : disabled   P(0)
- xpaas          : disabled   P(0)
$ minishift addons enable admin-user
Add-on 'admin-user' enabled
$ minishift start \
  --cpus 4 --memory 8192 \
  --openshift-version v3.6.0
...
```

Note: I'm using the latest OpenShift version in the example above. Your mileage may vary.
I'm in the process of updating the Templates for the latest releases (#19) and will update the reference docs regarding new features in `minishift` etc.
