### ISSUE TITLE
advantages comapred to Kuberntes Deployer

### ISSUE THREAD

**Issue by cforce** [donovanmuller/spring-cloud-dataflow-server-openshift#29]
Are there advantages using the OpenShift Deployer instead of the spring team managed kuberntes Deployer? I mean are there any OpenShift features used in this domain that the [Kubernetes Deployer](https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes) does not offer

**Comment by donovanmuller** [comment]
Hi @cforce,

The initial premise of a OpenShift specific deployer, was that the K8 deployer at the time did not use the OpenShift features of the [fabric8io/kubernetes-client](https://github.com/fabric8io/kubernetes-client) (on which both deployers rely for K8 API consumption) and therefore was not able to actually work in OpenShift. This was as early as OpenShift 1.2/3.2.

Hence I created OpenShift deployer by extending the K8 deployer but with the OpenShift specific tweaks to allow it to work within OpenShift. I haven't actually tested if the official K8 deployer now works on OpenShift or not (I assume it might) but since then some OpenShift specific feature have been made use of.

One example is the ability to support the `maven://` resource type in addition to the `docker://` resource type. The Maven resource type uses a [`BuildConfig`](https://docs.openshift.org/latest/dev_guide/builds/index.html) to enable deploying Maven resolved Spring Boot apps. See the [reference docs](https://donovanmuller.github.io/spring-cloud-dataflow-server-openshift/docs/1.2.1.RELEASE/reference/htmlsingle/#_support_for_maven_resource) for more. S2I builds are also planned to be supported in future (https://github.com/donovanmuller/spring-cloud-deployer-openshift/issues/36).

There are other features that OpenShift initially supported that upstream Kubernetes was lacking at the time (but has since been added). Some examples of these are DeploymentConfigs/Deployments, Service Accounts/RBAC, Routes/Ingress etc. The OpenShift deployer was able to use these features before the official K8 deployer. As these features are added, they are removed from this deployer and leveraged from the upstream K8 deployer where applicable.

Hopefully that answers your question?

If you'd like to see this deployer becomes an officially maintained Spring Cloud project then upvote [this issue](https://github.com/spring-cloud/spring-cloud-deployer/issues/222).

**Comment by donovanmuller** [comment]
Closed due to inactivity. Please reopen if more information is required...
