### ISSUE TITLE
Unable to specify dockerfile via deployment property

### ISSUE THREAD

**Issue by Anyx14** [donovanmuller/spring-cloud-dataflow-server-openshift#32]
The method for specifying a dockerfile via deployment properties described in the [Dockerfile Resolution Strategies](https://donovanmuller.github.io/spring-cloud-dataflow-server-openshift/docs/1.1.0.RELEASE/reference/htmlsingle/#_dockerfile_resolution_strategies) section of the documentation does not appear to work.

Using the following command in dataflow shell:
```
stream deploy --name ticktock --properties "spring.cloud.deployer.openshift.deployment.dockerfile=/tmp/deployer/Dockerfile"
```
Results in this error message:
```
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Only deployment property keys starting with 'app.' or 'deployer.' allowed, got 'spring.cloud.deployer.openshift.deployment.dockerfile'
```

Is this still the correct syntax for setting this property?

**Comment by donovanmuller** [comment]
@Anyx14 thanks for reaching out.

I believe the syntax should be:

```
```

**Comment by donovanmuller** [comment]
Actually, looking at the Spring Cloud Data Flow reference documentation with regards to [deployment properties](https://docs.spring.io/spring-cloud-dataflow/docs/1.2.3.RELEASE/reference/htmlsingle/#_deployment_properties), the syntax might actually be:

```
stream deploy --name ticktock --properties "deployer.xxx.openshift.deployment.dockerfile=/tmp/deployer/Dockerfile"
``` 

has been a while since I've had to pass in these properties so forgive me not knowing the exact syntax 😄

**Comment by Anyx14** [comment]
Thanks for the help.
Both of those methods work, but it looks like the first one is now deprecated.
